use_frameworks!

platform :ios, '8.0'

target 'KKHook_Example' do
  pod 'KKHook', :path => '../'

  target 'KKHook_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
